import Phaser from 'phaser';
import { GamePhase } from '../state/GamePhase';
import { HudTokens } from './layout/HudTokens';
export interface GameTopHudContext { primaryTitle?: string; secondaryTitle?: string; linkShards?: number; hideBrand?: boolean; }
/** Single player-facing header owner. Setup context is presentation-only. */
export class GameTopHUD {
  private readonly objects: Phaser.GameObjects.GameObject[]=[]; private readonly phases=new Map<GamePhase,Phaser.GameObjects.Text>(); private primary!:Phaser.GameObjects.Text; private secondary!:Phaser.GameObjects.Text; private beasts!:Phaser.GameObjects.Text; private energy!:Phaser.GameObjects.Text; private link!:Phaser.GameObjects.Text;
  constructor(private readonly scene:Phaser.Scene){const w=scene.scale.width; this.objects.push(scene.add.rectangle(w/2,35,w,70,HudTokens.colors.bgSurfaceDark,.96)); this.primary=scene.add.text(20,14,'BEAST LINK BATTLE',{fontFamily:HudTokens.fonts.family,fontSize:'17px',color:'#fff',fontStyle:'bold'}); this.secondary=scene.add.text(20,43,'BEAST RUSH',{fontFamily:HudTokens.fonts.family,fontSize:'10px',color:HudTokens.colors.textGold,fontStyle:'bold'}); this.objects.push(this.primary,this.secondary); ([['BeastRush','BEAST'],['EnergyRush','ENERGY'],['BattleSetup','SETUP'],['Battle','BATTLE'],['Result','RESULT']] as Array<[GamePhase,string]>).forEach(([p,l],i)=>{const t=scene.add.text(w/2-164+i*82,35,l,{fontFamily:HudTokens.fonts.family,fontSize:'10px',color:HudTokens.colors.textMuted,fontStyle:'bold'}).setOrigin(.5);this.phases.set(p,t);this.objects.push(t)});this.beasts=scene.add.text(w-210,29,'BEAST 0',{fontFamily:HudTokens.fonts.family,fontSize:'11px',color:HudTokens.colors.textBlue,fontStyle:'bold'});this.energy=scene.add.text(w-120,29,'ENERGY 0',{fontFamily:HudTokens.fonts.family,fontSize:'11px',color:HudTokens.colors.textGold,fontStyle:'bold'});this.link=scene.add.text(w-34,29,'◆0',{fontFamily:HudTokens.fonts.family,fontSize:'11px',color:'#7dd3fc',fontStyle:'bold'}).setOrigin(1,.5);this.objects.push(this.beasts,this.energy,this.link)}
  update(p:GamePhase,beasts:number,energy:number,context?:GameTopHudContext):void{this.primary.setText(context?.primaryTitle??'BEAST LINK BATTLE');this.secondary.setText(context?.secondaryTitle??p.replace(/([A-Z])/g,' $1').trim().toUpperCase());this.beasts.setText(`BEAST ${beasts}`);this.energy.setText(`ENERGY ${energy}`);this.link.setText(`◆${context?.linkShards??0}`);for(const[key,text]of this.phases)text.setColor(key===p?'#fbbf24':HudTokens.colors.textMuted)}
  setVisible(v:boolean):void{this.objects.forEach(o=>(o as unknown as Phaser.GameObjects.Components.Visible).setVisible(v))} destroy():void{this.objects.splice(0).forEach(o=>o.destroy())}
}
