import { AutonomousBattleModel, type EnemyFixture, P1V13A_SIGNATURE_RULES } from '../battle/AutonomousBattleModel';
import { BattleFormation } from '../battle/BattleFormation';
import { EnergyQueue } from '../energy/EnergyQueue';
import { V14G_ENERGY_RUSH_POOL } from '../energy/TacticalEnergyCatalog';
import { setupEnergyInventory } from './BattleSetupPresentation';
import { tacticalEnergyCastFeedback, tacticalEnergyControl, tacticalEnergyPlayerName } from './TacticalEnergyPresentation';
function ok(v: unknown, m: string): asserts v { if (!v) throw Error(`P1V14G2: ${m}`); }
function model(): AutonomousBattleModel { const f = new BattleFormation([{ contentId: 'beast-a', star: 1 }, { contentId: 'beast-c', star: 1 }, { contentId: 'beast-d', star: 1 }]); f.units.forEach((u,i)=>f.place(u.unitId,['front-1','mid-1','back-1'][i])); const es: EnemyFixture[]=[{enemyId:'d',slotId:'d',row:'Front',column:1,maxHp:100,damage:1,archetype:'Diver'}]; return new AutonomousBattleModel(f,es,P1V13A_SIGNATURE_RULES,{ 'unit-2':30,'unit-3':20 }); }
export function runP1V14G2Checks(): void { const q=new EnergyQueue(); ['energy-a','energy-b','energy-c','energy-d'].forEach(id=>q.addCharge(id)); const m=model(); const s=(m as unknown as {state:{enemies:Array<{targetUnitId?:string;engagedTargetId?:string}>}}).state; s.enemies[0].targetUnitId='unit-3'; const rescue=m.tacticalEnergyEligibility('energy-b',q); ok(rescue.availability==='suggested'&&rescue.suggestedReason==='DIVER PRESSURE','targeted backline diver pressure'); s.enemies[0].engagedTargetId='unit-2'; ok(m.tacticalEnergyEligibility('energy-b',q).suggestedReason==='DIVER PRESSURE','engaged mid pressure'); s.enemies[0].engagedTargetId='unit-1'; ok(m.tacticalEnergyEligibility('energy-b',q).suggestedReason==='DIVER PRESSURE','target OR engagement'); ['MEND','RESCUE','BREAK','PIERCE'].forEach((name,i)=>ok(tacticalEnergyPlayerName(`energy-${'abcd'[i]}`)===name,'catalog identity')); const ready=tacticalEnergyControl({energyId:'energy-c',kind:'Break',availability:'ready',reason:'ok'},1,false)!; ok(ready.stateLabel==='READY'&&ready.enabled&&!ready.suggested,'ready presentation'); const suggested=tacticalEnergyControl({energyId:'energy-c',kind:'Break',availability:'suggested',reason:'ok',suggestedReason:'FRONTLINE PRESSURE'},1,false)!; ok(suggested.stateLabel==='SUGGESTED'&&suggested.suggested&&suggested.reasonLabel==='FRONTLINE PRESSURE','suggested presentation'); const disabled=tacticalEnergyControl({energyId:'energy-c',kind:'Break',availability:'disabled',reason:'no-frontliner'},1,false)!; ok(!disabled.enabled&&disabled.reasonLabel==='NO FRONTLINER','disabled presentation'); ok(tacticalEnergyControl({energyId:'energy-d',kind:'Pierce',availability:'ready',reason:'ok'},1,true)?.reasonLabel==='PAUSED','pause override'); const inventory=setupEnergyInventory([{energyId:'energy-a',charges:2},{energyId:'energy-b',charges:1},{energyId:'energy-c',charges:0}]); ok(inventory.length===2&&inventory[0].displayName==='MEND'&&inventory[1].shortDescription==='Heal backline','setup catalog inventory'); ok(V14G_ENERGY_RUSH_POOL.join(',')==='energy-a,energy-b,energy-c,energy-d','active pool'); const result={success:true,energyId:'energy-b',kind:'Rescue' as const,reason:'ok' as const,targetUnitId:'unit-2',amount:18}; ok(tacticalEnergyCastFeedback(result,m.snapshot)?.includes('+18'),'actual result feedback'); ok(tacticalEnergyCastFeedback({...result,success:false},m.snapshot)===undefined,'failed has no success feedback'); }
