import { BeastRushPhaseTimer } from './BeastRushPhaseTimer';
import { ComboQualityTracker } from './ComboQualityTracker';
import { BattleQueue } from '../queue/BattleQueue';
function expect(value: unknown, label: string): asserts value { if (!value) throw new Error(`P1-V14C.1 check failed: ${label}`); }
export function runP1V14C1Checks(): void {
  const phase = new BeastRushPhaseTimer(12); let ends = 0; phase.onEnded(() => ends++); phase.start(); expect(phase.snapshot.remainingSeconds === 12 && phase.snapshot.active, 'phase starts immediately at 12'); phase.update(1); expect(Number(phase.snapshot.remainingSeconds) === 11, 'phase ticks before matching');
  const combo = new ComboQualityTracker(1.5); combo.registerValidMatch(); expect(combo.snapshot.currentStreak === 1, 'first match starts streak'); const beforeMatch = phase.snapshot.remainingSeconds; combo.registerValidMatch(); expect(Number(combo.snapshot.currentStreak) === 2 && combo.snapshot.windowSeconds === 1.5, 'within-window match increments and resets'); expect(phase.snapshot.remainingSeconds === beforeMatch, 'valid match cannot extend phase'); combo.update(1.5); expect(Number(combo.snapshot.currentStreak) === 0 && phase.snapshot.active, 'combo expiry does not end phase'); combo.registerValidMatch(); combo.breakStreak(); expect(Number(combo.snapshot.currentStreak) === 0 && phase.snapshot.remainingSeconds === beforeMatch, 'invalid break leaves phase time unchanged'); phase.update(99); expect(ends === 1, 'phase end fires once'); phase.update(1); expect(ends === 1, 'phase end stays once');
  const a = new BattleQueue(); const b = new BattleQueue(); for (let i = 0; i < 6; i++) { a.addBeastMatch('beast-a'); b.addBeastMatch('beast-a'); } const bestA: number = 6; const bestB: number = 2; expect(a.count('beast-a') === b.count('beast-a'), 'A/B quantity equal'); expect(bestA !== bestB, 'A/B quality can differ with same quantity'); const c = new BattleQueue(); const d = new BattleQueue(); for (let i = 0; i < 8; i++) c.addBeastMatch('beast-a'); for (let i = 0; i < 5; i++) d.addBeastMatch('beast-a'); expect(c.count('beast-a') !== d.count('beast-a'), 'C/D quantity can differ with same quality');
  phase.reset(); combo.reset(); expect(phase.snapshot.remainingSeconds === 12 && combo.snapshot.bestStreak === 0, 'new rush resets both signals');
}
